package com.moreoop.ObjectClass;

/*
Object class is inside the java.lang package
Object class is the default class that each and every class extend in internally
So, The object class is the top most class in the hierarchy of Inheritance of any class
But, java does not support the multiple inheritance, Object class is extended to
our super class
for example


    class A extends B

    but internally its:
    class B extends Object

    -> So, Object is the top most class in the hierarchy of inheritance in java

    Object Class have
        Core methods
            1. toString()
                Signature -> public String toString();
                it return the class@hashcode of the object by default
            2. equal()
                Signature -> public boolean equal(Object ob);
                by default it compare the references of the two objects (ob1 == ob2)
            3. hashCode()
                Signature -> public int hashCode();
                it return in Hex formate, if obj1.equal(obj2) is true then their
                hashCode has to be true. But the reverse might not be true.
                If equal() method is overridden, then it's our responsibility to
                override the hashCode() to follow the rule
            4. getClass()
                Signature -> public final Class <?> getClass();
                as it is final method that we cannot override.
                it returns the runtime class of an object

        Cloning
            5. clone()
                Signature -> protected Object clone() throws CloneNotSupported
                It create a shallow copy of an object by default, and it can be
                overridden if the marker Interface Clonable is implement to the class,
                and it also throws CloneNotSupported exception.

        Garbage Collection
            6. finalize()
                it execute just before the garbage collection run on the object
                it is deprecated because
                    its unpredictable
                    its unsafe
                    its unreliable

        Threads
            7. wait()
            8. notify()
            9. notifyAll()
            this will be study on multithreading

    when we write
    int[] arr = new int[5];
    even the array is a non-primitive, the Object class will come over it

*/

import java.util.Objects;

public class ObjectClassDemo {

    int num;
    String name;

    public ObjectClassDemo(int num, String name) {
        this.num = num;
        this.name = name;
    }


    //these are the methods inside the Object class

    @Override
    protected Object clone() throws CloneNotSupportedException {
        return super.clone();
    }

    // it returns a hash value
    @Override
    public int hashCode() {
        //here we generate our own hash code
        //return (this.num + (this.name == null?0:this.name.hashCode()));

        //also there is a built-in class in java.util package call "Objects"
        //it can do to job of generating this hash value
        return (Objects.hash(name,num));
    }


    @Override
    public boolean equals(Object obj) {

        //we can handle null pointer exceptions
        if(obj == null)
            return false;

        //we can handle classCastException
        if(obj.getClass() != this.getClass())
            return false;

        //if same object is compare
        if(obj == this)
            return true;

        ObjectClassDemo ob = (ObjectClassDemo) obj;
        return (this.num == ob.num && this.name == ob.name);
    }

    //to string is done on the core
    @Override
    public String toString() {
        return super.toString();
    }

    //finalized is deprecated
    @Override
    protected void finalize() throws Throwable {
        super.finalize();
    }

    public static void main(String[] args) {
        ObjectClassDemo ob1 = new ObjectClassDemo(1,"name1");
        ObjectClassDemo ob2 = new ObjectClassDemo(1,"name1");
        ObjectClassDemo ob3 = new ObjectClassDemo(2,"name1");

        //these print a int value hash code generated by an internal algo
        //this is used to check it is a same object or not
        System.out.println(ob1.hashCode());


        // > instanceof - is binary operator used to check an object is belonged to the class

        System.out.println(ob1 instanceof ObjectClassDemo);

        //used of getClass()
        System.out.println(ob1.getClass());
        System.out.println(ob1.getClass().getName());
        /*
            class A
            {
            }
            class B extends A
            {
            }
            psvm()
            {
                A ob1 = new A();
                A ob2 = new B();
                getClass() checks the object
                instanceof checks the reference
                ob2.getClass().getName() -> B
                ob2 instanceof B -> false because ob2 is an instance of A
            }


        */

        //use of equals method
        System.out.println(ob1.equals(ob2));
        System.out.println(ob1.equals(ob3));

        //use of hashCode() method
        System.out.println(ob1.hashCode());
        System.out.println(ob2.hashCode());
        System.out.println(ob3.hashCode());
    }
}
