package com.moreoop.ObjectClass;

//Object class is the default class that each and every class extend in internally
//So, The object class is the top most class in the hierarchy of Inheritance of any class
//even java does not support the multiple inheritance it is inherited internally
//for example
/*

    class A extends B

    but internally its:
    class A extends B, Object
    -> So, Object is the top most class in the hierarchy of inheritance in java
 */

public class ObjectClassDemo {

    //these are the methods inside the Object class

    @Override
    protected Object clone() throws CloneNotSupportedException {
        return super.clone();
    }

    // it returns a hash value
    @Override
    public int hashCode() {
        return super.hashCode();
    }


    @Override
    public boolean equals(Object obj) {
        return super.equals(obj);
    }

    //to string is done on the core
    @Override
    public String toString() {
        return super.toString();
    }

    @Override
    protected void finalize() throws Throwable {
        super.finalize();
    }

    public static void main(String[] args) {
        ObjectClassDemo ob = new ObjectClassDemo();
        //these print a int value hash code generated by an internal algo
        //this is used to check it is a same object or not
        System.out.println(ob.hashCode());

        //some other methodes/operator used with objects are
        // 1> instanceof - is binary operator used to check an object is belong to the class
        // 2> getClass - used to check the class of the object, it have many methode of its own

        System.out.print(ob instanceof ObjectClassDemo);
    }
}
